# Generated by Django 4.1.7 on 2024-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_productcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
